version: "3.9" 

services: 
  redis: 
    image: redis 
    ports: 
      - 6379:6379 
  
  mongodb: 
    image: mongo:4.4.3 
    ports: 
      - 27017:27017 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=password 